blueprint:
  name: "E2002 Remote Control"
  domain: automation
  input:
    device:
      name: "STYRBAR E2002 Remote Control"
      selector:
        device: {}

triggers:
  trigger: state
  entity_id: !input device

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on
        sequence: !input on
